# Generated by Django 2.0.4 on 2018-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('shortenedUrl', models.CharField(blank=True, max_length=6, unique=True)),
            ],
        ),
    ]
